name: Alpha Release

on:
  push:
    branches: master
    paths-ignore: ['**/CHANGELOG.md', '**/package.json']

jobs:
  alpha-release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Set git user
      run: git config --global user.name 'cloudoki-deploy'; git config --global user.email 'general@cloudoki.com'

    - name: Publish Release
      run: npx @cloudoki/donderflow@1.0.0-alpha.5 --preid alpha
